### ISSUE TITLE
Error: could not find function "as.data.frame.sm_response"

### ISSUE THREAD

**Issue by klittle314** [cloudyr/Rmonkey#6]
Hi Tom, thanks for your package, helping me with a project.   Am talking to my SurveyMonkey account and extracting information about my surveys, was moving along fast.

But I am getting an error in calling the as.data.frame.sm_response and as,data.frame.sm_response_list functions, R thinks these don't exist?

Rmonkey version 0.2.11 and R version 3.2.0, Windows.

thanks, can provide more details....alternative is just to slog thru the survey data list myself and build a data frame...

Kevin Little

**Comment by leeper** [comment]
Hi Kevin, what's the exact code you're using? You shouldn't try to call the `as.data.frame.sm_response`, etc. functions directly but instead allow R to engage S3 method dispatch on the objects (i.e., just call `as.data.frame` on the response object). If you want to call the methods directly, you have to use `:::` notation (as in `Rmonkey:::as.data.frame.sm_response`, etc.) because those methods are not exported from the package namespace.

**Comment by klittle314** [comment]
Thanks Tom, I think I grasp what you're saying.  

My survey has a mix of multiple choice and free text fields and that may be causing me trouble.   

I have defined my respondent list as resp_list and my survey as ID_survey[[1]].   These objects exist in the Global Environment and match what I see in the SurveyMonkey user interface.

When I run the suggested function in your help description
a <- getresponses(lapply(resp_list[[1]],function(x) `[`,'respondent_id'),ID_survey[[1]])

I get an error message:

a <- getresponses(lapply(resp_list[[1]],function(x) `[`,'respondent_id'),ID_survey[[1]])
Error in FUN(X[[i]], ...) : unused argument ("respondent_id")
Called from: inherits(respondents, "sm_respondent")

To build my intuition, I am working my way through the survey and pulling out the responses (which are ID numbers that need to be converted to human sensible labels).

thanks again.

kevin

**Comment by leeper** [comment]
I think you can simplify your code and that will solve this problem `getresponses` can accept either a vector of respondent IDs or a list of "sm_respondent" objects, so you should be able to just do:

```R
# get first respondent's answers
a <- getresponses(resp_list[[1]], ID_survey[[1]])
```

Or even:

```R
# get all responses
a <- getresponses(resp_list, ID_survey[[1]])
```

Once you've run that code, you should be able to just call `as.data.frame(a)` to get it all back as a neat data.frame.

(The code you're showing there suggests you're trying to pass a list of response IDs (`lapply` always returns a list, not an atomic vector), rather than either a list of "sm_respondent" objects or a vector of response ids, so `getresponses` doesn't know what you're trying to do.)

**Comment by klittle314** [comment]
Thanks, this works for a specific individual response but there appears to be something in the data structure causing an error, taking the data apart and trying to understand.

![image](https://cloud.githubusercontent.com/assets/3459577/9249542/6e715828-418b-11e5-985e-6fc0c5d90a59.png)

**Comment by klittle314** [comment]
Looks like the problem is that at least one of the responses has missing data, so the function call blows up, can't make a dataframe because unequal number of records among respondents.  digging more.

**Comment by leeper** [comment]
@klittle314 I believe I have fixed this. Can you reinstall from GitHub and let me know if it's work for you?

**Comment by klittle314** [comment]
Yes!  Just downloaded revised package and successfully created a survey using the createsurvey function.   Thanks again for working on the package 

(now we just need to work thru SurveyMonkey idiosyncracies with survey title strings that make it painful to get surveylist function happy--this appears to be an issue with the SurveyMonkeyAPI, not your function as I can confuse SurveyMonkey using the API browser interface--the character string for a survey title looks correct but SurveyMonkey can't interpret the string to return the integer ID.....sheesh.)

**Comment by leeper** [comment]
@klittle314 Excellent!
